### ISSUE TITLE
Installer Error

### ISSUE THREAD

**Issue by elgrunt0** [hmemcpy/SnagitImgur#21]
Soon as installer is launched, it prompts: http://i.imgur.com/tKTINVJ.png

It's being run from local drive
Windows 8.1 x64. 
SnagitImgur_1.0.1.msi - 602KB

**Comment by tek0011** [comment]
Also same issue here.  Windows 8.1 Snagit 12

**Comment by hmemcpy** [comment]
Sorry for this taking a very long time...
(if relevant), could you please try the latest version?

**Comment by tek0011** [comment]
Sorry.  4 months for a support reply.  I have already switched to PicPick.
