### ISSUE TITLE
Not adding URL to clipboard and no pop up notification

### ISSUE THREAD

**Issue by lonelymonk** [hmemcpy/SnagitImgur#24]
Love this tool it's so useful but it's not copying the URL to the clipboard for me or triggering the popup. Using Snagit 12.3.2 and SnagitImgur 1.4.0

Thanks!

**Comment by hmemcpy** [comment]
Hmm, sorry about that. Does it open the browser, at least?
If so, please look in the (new) options - down arrow on the icon, select Option.
Those are probably unchecked...

I will make better defaults.

**Comment by hmemcpy** [comment]
Hi again,
Can you please try this version: https://dl.dropboxusercontent.com/u/2323661/SnagitImgur.zip
Just copy it on top of the existing files, located in `%LOCALAPPDATA%\TechSmith\Snagit\Accessories\{EDA9F1DD-85B9-44F6-9D3C-125B2DD1109D}`
I've added some additional logging, maybe it will help me understand the problem better.

**Comment by hmemcpy** [comment]
In any event, I just pushed v1.5 that fixes this issue (hopefully for good)!
Please give it a try!
