### ISSUE TITLE
When sharing to imgur, snagit crashes after uploading image.

### ISSUE THREAD

**Issue by delize** [hmemcpy/SnagitImgur#28]
Hello,

I have just recently have had issues that when uploading or sharing a file to imgur, snagit crashes prior to giving me a link to copy. The photo itself is uploaded, however, I have to navigate to imgur via my browser to grab the link.

It would be nice if the crash issues were resolved.

**Comment by bfwlegend** [comment]
having the same issue

**Comment by adamteece** [comment]
Having the same issue, screenshot hosted on droplr - http://d.pr/i/157RW/1zPLalDy

**Comment by tomfuegue** [comment]
Same issue here. 

I'm using Windows 10 Home x64.

**Comment by tomfuegue** [comment]
Ok, I've the solution:

1º) Go to Program Files (x86)/TechSmith/Snagit 12 and right click on to archives:

   • Snagit32.exe
   • SnagitEditor.exe

The choose "Properties" > Compatibility > Tick "Run the program in administrator mode".

Second, "Compatibility mode" > Run this program in compatibility mode for: choose Windows 7 or 8, for me works 8.

Make it with this two archives .exe

Voilà, the browser opens after you share the capture with imgur plugin!!!.

Sorry my english, I'm from Spain.

**Comment by bfwlegend** [comment]
Thanks for the update, your English was perfectly, fine will try it out!

**Comment by delize** [comment]
Hey tomfuegue,

Yeah, your English is fine. :)

Further testing, you don't actually have to enable "Run the program in administrator mode."
Enabling "Compatibility Mode for all users" in Windows 8 allows the program to run perfectly fine. I think it is safe to say that we can close this issue now. :)
