### ISSUE TITLE
Using extension from a hotkey profile on Windows 10 causing Snagit to crash

### ISSUE THREAD

**Issue by dsifford** [hmemcpy/SnagitImgur#29]
This doesn't happen every time, but every 2 or 3 times I use this my snagit instance crashes completely and requires a reboot. 

Not sure if there is a way to see error logs, but if there is let me know and I'll post them.

**Comment by ebmp19** [comment]
Hey i've created a fix to what sounds like your problem (I had the same one). Until the developer addresses the problem directly you can install the current version he has released with the bug and use these instructions to update it  with my changes after installing. 

1. Download my branch by going here and pressing download zip - https://github.com/ebmp19/SnagitImgur/tree/FixedWindows10Crash

2. Extract the zip and run the file build.cmd (press more info then run anyway if there's a security error)

3. Close Snagit

4. Browse to the /output/Release folder and copy everything to %userprofile%\AppData\Local\TechSmith\SnagIt\Accessories\{EDA9F1DD-85B9-44F6-9D3C-125B2DD1109D}

**Comment by dsifford** [comment]
Thanks @ebmp19 ! I made the switch over to full-time Linux now, so unfortunately I won't be able to try your fix, but I'm sure others will appreciate it! 😊
