### ISSUE TITLE
Uploading to Imgur account

### ISSUE THREAD

**Issue by mathonwy1** [hmemcpy/SnagitImgur#31]
Hey dude,

Great plug-in.  I love it.  It's really helped me a lot.

Question.  Is it possible to do the upload into an existing Imgur account?  I want to keep all of my pictures together and accessible.

Thanks again for your work on this!

-math

**Comment by ebmp19** [comment]
The plugin already has this functionality you just go into the snagit editor -> change to the share tab -> press the down arrow next to the imgur icon -> press account.

**Comment by mathonwy1** [comment]
Got it.

Thanks for the reply!
