### ISSUE TITLE
Add option to copy the uploaded image URL to clipboard

### ISSUE THREAD

**Issue by hmemcpy** [hmemcpy/SnagitImgur#4]

**Comment by jedicolt** [comment]
I came here looking for this as well. It would be nice to not have the image automatically open up in a browser window. Many times, I just need the URL to paste into a chat window. Thanks for the work on this plugin.

**Comment by itsBasir** [comment]
I was looking for this option too. Would be great if we could have this ability!

**Comment by hmemcpy** [comment]
I know it's few years too late... but I finally added a clipboard copy and a popup, instead of opening the browser :)
![image](https://cloud.githubusercontent.com/assets/601206/7735263/cc60e6e4-ff44-11e4-902c-7496770a697f.png)

**Comment by jedicolt** [comment]
Dude that is awesome. Thanks so much for your work on this!
