### ISSUE TITLE
Add Imgur Account integration

### ISSUE THREAD

**Issue by lorezcrash** [hmemcpy/SnagitImgur#7]
I'll happily put some money towards this. LMK.

**Comment by tvl83** [comment]
I would like to bump this request :)

**Comment by hmemcpy** [comment]
I'm sorry it took *so long*... but after 3 years I am FINALLY happy to report that the new version (v1.2) supports imgur accounts :)

Please download it from this link: https://github.com/hmemcpy/SnagitImgur/releases/download/1.2/SnagitImgur_1.2.msi
